### ISSUE TITLE
表格关键字

### ISSUE THREAD

**Issue by 251623126** [meethigher/cpdaily-submit#1]
老哥关于筛选关键字，我们学校表格有否也有是，怎么填关键字啊

**Comment by meethigher** [comment]
> 老哥关于筛选关键字，我们学校表格有否也有是，怎么填关键字啊

如果都是单选的话，把要选的选项整到配置文件里，然后按顺序读取吧。里面代码要改了。

**Comment by 251623126** [comment]
嘿嘿不太会，老哥能适配吗

**Comment by meethigher** [comment]
> 嘿嘿不太会，老哥能适配吗

行，倒是也不麻烦，我看看

**Comment by 251623126** [comment]
> > 嘿嘿不太会,老哥能适配吗
> 
> 行,倒是也不麻烦,我看看

**Comment by 251623126** [comment]
> > > 嘿嘿不太会,老哥能适配吗
> > 
> > 
> > 行,倒是也不麻烦,我看看

![0AB )C$DL5G~W~W2`NDOE5B](https://user-images.githubusercontent.com/49135483/104139673-079a4180-53e8-11eb-9450-926930a90f13.png)
表是这个样子的

**Comment by meethigher** [comment]
> > > > 嘿嘿不太会,老哥能适配吗
> > > 
> > > 
> > > 行,倒是也不麻烦,我看看
> 
> ![0AB )C$DL5GWW2`NDOE5B](https://user-images.githubusercontent.com/49135483/104139673-079a4180-53e8-11eb-9450-926930a90f13.png)
> 表是这个样子的

第一个是什么？填空？

**Comment by meethigher** [comment]
> > > > 嘿嘿不太会,老哥能适配吗
> > > 
> > > 
> > > 行,倒是也不麻烦,我看看
> 
> ![0AB )C$DL5GWW2`NDOE5B](https://user-images.githubusercontent.com/49135483/104139673-079a4180-53e8-11eb-9450-926930a90f13.png)
> 表是这个样子的

你这个应该是子墨那个吧，不能用吗

**Comment by 251623126** [comment]
> > > > > 嘿嘿不太会,老哥能适配吗
> > > > 
> > > > 
> > > > 行,倒是也不麻烦,我看看
> > 
> > 
> > ![0AB )C$DL5GWW2`NDOE5B](https://user-images.githubusercontent.com/49135483/104139673-079a4180-53e8-11eb-9450-926930a90f13.png)
> > 表是这个样子的
> 
> 第一个是什么？填空？

省级联动地址
![Uploading Screenshot_2021-01-11-08-43-54-290_com.wisedu.cpd.jpg…]()

**Comment by meethigher** [comment]
> 嘿嘿不太会,老哥能适配吗
> 
> 行,倒是也不麻烦,我看看
> 
> 
> 表是这个样子的
> 
> 第一个是什么？填空？
> 
> 省级联动地址

兄弟，我好像帮不上忙了，因为那个type是1的，我们学校虽然有，但那个是异动出行，我没填过，所以不知道他的格式是啥样的。这个得看到格式才行。

**Comment by 251623126** [comment]
> > 嘿嘿不太会,老哥能适配吗
> > 行,倒是也不麻烦,我看看
> > 表是这个样子的
> > 第一个是什么？填空？
> > 省级联动地址
> 
> 兄弟，我好像帮不上忙了，因为那个type是1的，我们学校虽然有，但那个是异动出行，我没填过，所以不知道他的格式是啥样的。这个得看到格式才行。

这个吗
![Screenshot_2021-01-11-08-58-01-167_com guoshi htt](https://user-images.githubusercontent.com/49135483/104140215-4d0c3e00-53eb-11eb-9b8f-70a384f9c580.jpg)

**Comment by meethigher** [comment]
> > > 嘿嘿不太会,老哥能适配吗
> > > 行,倒是也不麻烦,我看看
> > > 表是这个样子的
> > > 第一个是什么？填空？
> > > 省级联动地址
> > 
> > 
> > 兄弟，我好像帮不上忙了，因为那个type是1的，我们学校虽然有，但那个是异动出行，我没填过，所以不知道他的格式是啥样的。这个得看到格式才行。
> 
> 这个吗
> ![Screenshot_2021-01-11-08-58-01-167_com guoshi htt](https://user-images.githubusercontent.com/49135483/104140215-4d0c3e00-53eb-11eb-9b8f-70a384f9c580.jpg)

对的，我想知道他提交的格式是怎样的

**Comment by 251623126** [comment]
> > > > 嘿嘿不太会,老哥能适配吗
> > > > 行,倒是也不麻烦,我看看
> > > > 表是这个样子的
> > > > 第一个是什么？填空？
> > > > 省级联动地址
> > > 
> > > 
> > > 兄弟，我好像帮不上忙了，因为那个type是1的，我们学校虽然有，但那个是异动出行，我没填过，所以不知道他的格式是啥样的。这个得看到格式才行。
> > 
> > 
> > 这个吗
> > ![Screenshot_2021-01-11-08-58-01-167_com guoshi htt](https://user-images.githubusercontent.com/49135483/104140215-4d0c3e00-53eb-11eb-9b8f-70a384f9c580.jpg)
> 
> 对的，我想知道他提交的格式是怎样的

来了来了应该是它
![Screenshot_2021-01-11-09-05-30-207_com guoshi htt](https://user-images.githubusercontent.com/49135483/104140373-4500ce00-53ec-11eb-8b09-5f1053867ab6.jpg)
